export const DEFAULT_SCREENSHOT_PRESET_ID = "iphone-6-5";

export const DEFAULT_SCREENSHOT_WIDTH = 1284;
export const DEFAULT_SCREENSHOT_HEIGHT = 2778;
export const DEFAULT_SCREENSHOT_ASPECT_RATIO_CSS = `${DEFAULT_SCREENSHOT_WIDTH} / ${DEFAULT_SCREENSHOT_HEIGHT}`;

export const LEGACY_DEFAULT_SCREENSHOT_WIDTH = 1290;
export const LEGACY_DEFAULT_SCREENSHOT_HEIGHT = 2796;

export const DUMMY_TEMPLATE_ASSET_ID = "dummy-template";
export const DUMMY_TEMPLATE_ASSET_FILENAME = "dummy-template.svg";

export const SCREENSHOT_OPAQUE_BACKGROUND_HEX = "#FFFFFF";
